name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read

jobs:
  unix_tests:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 9
        platform: x64
        
    - name: Testing printf
      run: |
        gcc --version
        gcc -std=c11 -o test.exe test.c
        ./test.exe

  win_tests:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        cygwin: 1
        platform: x64
        
    - name: Testing printf
      run: |
        gcc --version
        gcc -std=c11 -o test.exe test.c
        ./test.exe

  mac_tests:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
        
    - name: Testing printf
      run: |
        gcc --version
        gcc -std=c11 -o test.exe test.c
        ./test.exe
